### ISSUE TITLE
Incluir nota sobre como leer los datos en archivos .sav

### ISSUE THREAD

**Issue by FvD** [ixpantia/opendataday2020#4]
EL INEC de Costa Rica tienen un [Programa Acelerado de Datos INEC / Costa Rica](http://sistemas.inec.cr/pad4/index.php/home) a travez del cual se pueden acceder diversos conjuntos de datos. Los datos se presentan en un formato con la extensión `.sav` el cual require dar unos pasos antes de leerlo.

**Comment by germanretana** [comment]
Cerrado con PR https://github.com/ixpantia/opendataday2020/pull/5
